version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: car-gallery-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: car_expo
      MYSQL_USER: admin
      MYSQL_PASSWORD: password123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./deployment/rds-setup.sql:/docker-entrypoint-initdb.d/02-data.sql
    networks:
      - car-gallery-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Backend API
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: car-gallery-backend
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 4000
      DB_HOST: mysql
      DB_USER: admin
      DB_PASS: password123
      DB_NAME: car_expo
    ports:
      - "4000:4000"
    networks:
      - car-gallery-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/api/types"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend (Nginx)
  frontend:
    image: nginx:alpine
    container_name: car-gallery-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:80"
    volumes:
      - ./Frontend:/usr/share/nginx/html
      - ./deployment/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - car-gallery-network

volumes:
  mysql_data:

networks:
  car-gallery-network:
    driver: bridge