apiVersion: v1
kind: Namespace
metadata:
  name: car-gallery
---
apiVersion: v1
kind: Secret
metadata:
  name: car-gallery-secrets
  namespace: car-gallery
type: Opaque
data:
  # Base64 encoded values - replace with your actual RDS credentials
  # Use: echo -n 'your-value' | base64
  db-host: eW91ci1yZHMtZW5kcG9pbnQucmRzLmFtYXpvbmF3cy5jb20=  # your-rds-endpoint.rds.amazonaws.com
  db-user: YWRtaW4=  # admin
  db-pass: eW91cnBhc3N3b3Jk  # yourpassword
  db-name: Y2FyX2V4cG8=  # car_expo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: car-gallery-config
  namespace: car-gallery
data:
  NODE_ENV: "production"
  PORT: "4000"